// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectFlorea.Data;

#nullable disable

namespace ProiectFlorea.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506155841_AddLocationFields")]
    partial class AddLocationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ProiectFlorea.Models.TemperatureReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("longitude");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("temperature_c");

                    b.Property<int>("VoltageMv")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("voltage_mv");

                    b.HasKey("Id");

                    b.ToTable("TemperatureReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
